name: webapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-72.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  common:
    path: ./common

  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.5.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  lottie: ^2.6.0
  search_cep: ^4.0.2
  file_picker: ^6.0.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.3
  flutter_speed_dial: ^7.0.0
  crypto: ^3.0.3
  easy_sidemenu: ^0.5.0
  excel: ^3.0.0
  path: ^1.8.3
  firebase_storage: ^12.3.2
  percent_indicator: ^4.2.3
  get: ^4.6.6
  url_launcher: ^6.2.1
  data_table_2: ^2.5.15
  flutter_side_menu: ^0.4.0
  flutter_animate: ^4.5.0
  easy_stepper: ^0.8.3
  flutter_dotenv: ^5.1.0
  syncfusion_flutter_charts: ^27.1.51
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/images/
    - assets/icons/
    - dotenv
