// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXFWij7iTEu91CW4S8dkDQqs1AMF0MmK4',
    appId: '1:934519095067:web:17bfeb64943459c6d51dbe',
    messagingSenderId: '934519095067',
    projectId: 'pcj-catequese',
    authDomain: 'pcj-catequese.firebaseapp.com',
    storageBucket: 'pcj-catequese.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrrYA7VIGGra49Wgc5-eIoba0nDl1DpWw',
    appId: '1:934519095067:android:a3ca7498f0c374a1d51dbe',
    messagingSenderId: '934519095067',
    projectId: 'pcj-catequese',
    storageBucket: 'pcj-catequese.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXpL3pLfha_8e3UtTtS_qqNKdt4ygnOG0',
    appId: '1:934519095067:ios:751829cbbb6b1931d51dbe',
    messagingSenderId: '934519095067',
    projectId: 'pcj-catequese',
    storageBucket: 'pcj-catequese.appspot.com',
    iosBundleId: 'com.example.webapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXpL3pLfha_8e3UtTtS_qqNKdt4ygnOG0',
    appId: '1:934519095067:ios:1fb3b0017f155ffed51dbe',
    messagingSenderId: '934519095067',
    projectId: 'pcj-catequese',
    storageBucket: 'pcj-catequese.appspot.com',
    iosBundleId: 'com.example.webapp.RunnerTests',
  );
}
